### ISSUE TITLE
Recompiling the Linux Kernel

### ISSUE THREAD

**Issue by marianneR** [the-snowwhite/soc-image-buildscripts#6]
Question about soc-image for DE0_nano_SoC:
1) Is this the correct repo for the following image ?
  http://deb.machinekit.io/uploads/de0-nano/debian-8.5-console-armhf-2017-02-14/

2) What is the best way to recompile the Linux Kernel to enable CMA ? I would like to ask an expert before trying something that may not be possible.

**Comment by the-snowwhite** [comment]
@marianneR  Sorry for the delay did you find answers elsewhere ?

While these build scripts are the origin reference for the above referenced image that image is built from  Robert Nelsons online "Omap" Image builder.

The image (top post) in this thread is the latest published image built from here:
 https://groups.google.com/forum/#!searchin/machinekit/de10$20nano%7Csort:date/machinekit/BPRQpoyvFm8/JrXmzp1uAQAJ

What purpose are you using CMA for .. Framebuffer ?
If that the case this is allready enabled via the alt vip framebuffer patch (CONFIG_DMA_CMA=y   + some more).
